build:
  environment:
    php: "8.4"

  dependencies:
    before:
      - composer install --no-interaction --prefer-dist
      - npm install

  tests:
    before:
      - npm test

checks:
  php:
    code_rating: true
    duplication: true
