#!/usr/bin/env php
<?php
/**
 *
 * Copyright (C) 2026  TheatreCMS Team (https://theatrecms.dev)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * Deprecated: use `bin/theatrecms user:create-admin`. This wrapper forwards its arguments
 * there and will be removed in a future release.
 */

if (PHP_SAPI !== 'cli') {
    exit(1);
}

fwrite(STDERR, "./create-admin is deprecated; use bin/theatrecms user:create-admin instead.\n");

$_SERVER['argv'] = array_merge([__DIR__ . '/bin/theatrecms', 'user:create-admin'], array_slice($_SERVER['argv'], 1));
$_SERVER['argc'] = count($_SERVER['argv']);

require __DIR__ . '/bin/theatrecms';
