openapi: 3.1.0
info:
  title: Theatre CMS API
  description: Theatre CMS API
  version: 0.0.1
servers:
  - url: 'http://theatrecms.ddev.site/api'
paths:
  /people:
    get:
      summary: Get People
      description: Retrieve a list of people from the Theatre CMS.
      responses:
        '200':
          description: A list of people.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
    post:
      summary: Create Person
      description: Create a new person in the Theatre CMS.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Person created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '500':
          description: Internal Server Error
  /people/{id}:
    get:
      summary: Get Person by ID
      description: Retrieve a specific person by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single person.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Person not found.
    put:
      summary: Update Person
      description: Update an existing person in the Theatre CMS.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: Person updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '500':
          description: Internal Server Error
    delete:
      summary: Delete Person
      description: Delete a person from the Theatre CMS.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Person deleted successfully.
        '404':
          description: Person not found.
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        biography:
          type: string
          example: An accomplished actor known for various roles.
        headshotUrl:
          type: string
          format: uri
          example: 'https://example.com/headshot.jpg'
    Work:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Hamlet
        description:
          type: string
          example: A Shakespearean tragedy about the Prince of Denmark.
        creators:
          type: array
          items:
            $ref: '#/components/schemas/Person'